%% FILENAME: gif-generation.mmd
%% AUTHOR: Zachary Krepelka
%% DATE: Saturday, November 22nd, 2025
%% ABOUT: Bad Apple!! but it's a terminal multiplexer
%% ORIGIN: https://github.com/zachary-krepelka/tmux-bad-apple.git
%% UPDATED: Monday, April 20th, 2026 at 9:36 PM

%%{
  init: {
    "class": {
      "hideEmptyMembersBox": true
    }
  }
}%%

classDiagram

  direction TB

  README.md ..> exhibit0.gif
  README.md ..> exhibit1.gif
  README.md ..> exhibit2.gif
  README.md ..> exhibit3.gif

  exhibit0.gif --> exhibit0.cast
  exhibit1.gif --> exhibit1.cast
  exhibit2.gif --> exhibit2.cast
  exhibit3.gif --> exhibit3.cast

  exhibit0.cast --> exhibit0.play
  exhibit1.cast --> exhibit1.play
  exhibit2.cast --> exhibit2.play
  exhibit3.cast --> exhibit3.play

  exhibit0.play --> playwright.sh
  exhibit1.play --> playwright.sh
  exhibit2.play --> playwright.sh
  exhibit3.play --> playwright.sh

  playwright.sh <-- recording.tmux.conf
